<a href="https://colab.research.google.com/github/Laura9704/Talento_Tech/blob/main/Clase_16_de_febrero_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Clase 16 de febrero 2026**

## **Repaso de basico**

* **lista**: contiene varios datos, comparacion con excel es una columna con n registros

* **numeros enteros (int) y decimales(float)**: los int son los numeros que pertnecen a los numeros naturales, los float son los numeros pertenecientes a los reales, esta informacion tiene limitado el espacio de datos a guardar

recordatorio: en Colab guarda un nuemro con 4299 posiciones/cifreas.

* **Booleanos:** representan el estado falso(False) y verdadero(True) solo dos estados

* **Char or String**: representan caracteres cortos( a,b,c,1,2,3) o cadenas de palabras( hola, mama, dia de amor y amistad) estos se caracterizan por usar "" comillas dobles o ''simples. Ejemplo:  'a' , 'hola',"hola", "Hola es el dia del amor y la amistad"

In [ ]:
#tipo string

nombres="Maria"
apellidos="Lopez Gercia"

#tipo entero
Edad=50
num_doc=106023977

#tipo float
altura= 1.66

#tipo booleano
Diabetica=False
Cedula= True

#imprimri o mostrar en pantalla individualmente
print(nombres)
print(apellidos)
print(num_doc)
print(Edad)
print(altura)
print(Diabetica)
print(Cedula)

#imprimir en frase
#forma 1
print( f"la paciente {nombres} {apellidos} con {Edad} y {altura} es diebetica:{Diabetica} ")
#con condicioneal

if Diabetica==True:
  print( f"la paciente {nombres} {apellidos} con {Edad} y {altura} es diebetica")
else:
  print( f"la paciente {nombres} {apellidos} con {Edad} y {altura} no es diebetica")

if Cedula == True:
  print( f"la paciente {num_doc} con {Edad} y {altura} tiene en sus examenes de diabetis es {Diabetica}")
else:
  print( f"la paciente {num_doc} con {Edad} y {altura} no tiene en sus examenes de diabetis es {Diabetica}")

#forma 2
print("Mentor: ", nombres+" "+apellidos)

Maria
Lopez Gercia
106023977
50
1.66
False
True
la paciente Maria Lopez Gercia con 50 y 1.66 es diebetica:False
la paciente Maria Lopez Gercia con 50 y 1.66 no es diebetica
la paciente 106023977 con 50 y 1.66 tiene en sus examenes de diabetis es False
Mentor:  Maria Lopez Gercia

### **Listas**

permiten generar registos en forma lineal(horizantal) en n posiciones de informacion, esta puede ser modifcado por diversos comandos.

In [ ]:
#listas

nombres={"ana","carme","luis"}
edades={35,50,16}
varios={"cc",True,"talla"}

print("\n\nlistas")
print(nombres)
print(edades)
print(varios)

#modifcar listas

mi_lista = [10, 20, 30]
print("\n\noriginal\n",mi_lista)
mi_lista[1] = 25
print(" modifcado por posicion\n",mi_lista)
mi_lista.insert(1, 20)
print("modifcado por comando insert",mi_lista)
mi_lista.append(20)
print("modifcado por comando appened",mi_lista)
mi_lista.remove(20) # otra forma es indicar la posicion dentro de la lista edades[2]
print("modificar eliminando datos con remove", mi_lista)
mi_lista.insert(1, 20)
mi_lista.pop(2)
print("modificar eliminando datos con pop e insertado un dato en la posicion del dato eliminado", mi_lista)

### **Tuplas**

son datos que no se pueden modificar, se ingresan con () y comas , para la separacion de los datos

In [ ]:
print("tupla abc es",tuple('abc'))
print( "tuple( [1, 2, 3] ) es" ,tuple( [1, 2, 3] ) )
print("vacia es", tuple())


#ejemplo de tuplas

coordenadas=(35,155,28,0)
print("Coordenadas: ", coordenadas)
longitud=coordenadas[0]
print("Longitud: ", longitud)
latitud=coordenadas[1]
print("Latitud: ", coordenadas[1])

tupla abc es ('a', 'b', 'c')
tuple( [1, 2, 3] ) es (1, 2, 3)
vacia es ()
Coordenadas:  (35, 155, 28, 0)
Longitud:  35
Latitud:  155

** ingreso de datos**

se implementa el comando input() para capturar la informacion ingresado, estos datos se guardan en formato string es decir en carcateres tipo texto

se usan coamndos que engloban el input para la conversion del dato

In [ ]:
dato=input("ingrese un dato: ")
dato

ingrese un dato: 55

'55'

In [ ]:
dato=input("ingrese un dato: ")
dato

ingrese un dato: maria

'maria'

lo imprime como numero ya que fue convertido como entero

In [ ]:
edad = int(input("Ingrese su edad: "))
edad

Ingrese su edad: 18

18

### **operaciones**

hay funciones que se pueden implementar atraves de los simbolos +,-,*,/,**. o se implementan liberias para el calculo como numpy

imprime datos tipo float con limitacion de cifras decimales

In [ ]:
edad = float(input("Ingrese su edad: "))
op=edad/7
print(f"op: {op}")
print(f"op: {op:.4f}")

Ingrese su edad: 19
op: 2.7142857142857144
op: 2.7143

### Tablas dataframe

In [ ]:
import pandas as pd
# format 1
dic={"name":     ["Lyn" ,"Carlos"],
     "last_name":["joun","Gia"],
     "Years":    [   20 ,  15],
     "weight":   [   50 ,  45],
     "height":   [  160 , 158]}
dic

{'name': ['Lyn', 'Carlos'],
 'last_name': ['joun', 'Gia'],
 'Years': [20, 15],
 'weight': [50, 45],
 'height': [160, 158]}

In [ ]:
print(dic)

{'name': ['Lyn', 'Carlos'], 'last_name': ['joun', 'Gia'], 'Years': [20, 15], 'weight': [50, 45], 'height': [160, 158]}

In [ ]:
df=pd.DataFrame(dic)
df

     name last_name  Years  weight  height
0     Lyn      joun     20      50     160
1  Carlos       Gia     15      45     158

In [ ]:
df["name"]=df['name'].str.lower()
df["last_name"]=df['last_name'].str.lower()
df

     name last_name  Years  weight  height
0     lyn      joun     20      50     160
1  carlos       gia     15      45     158

In [ ]:
#format 2

#create n value lists
#name
value_n_list=["jim","juan","jhon"]
#last_name
values_ln_list=["hook","lin","par"]
#hieght
values_h_list=[150,160,170]
#weight
values_w_list=[50,60,70]

print(value_n_list)

['jim', 'juan', 'jhon']

In [ ]:
#create dictionary: use key:value
tb_dict= {"name":value_n_list,
          "last_name":values_ln_list,
          "height":values_h_list,
          "weight":values_w_list}
tb_dict

{'name': ['jim', 'juan', 'jhon'],
 'last_name': ['hook', 'lin', 'par'],
 'height': [150, 160, 170],
 'weight': [50, 60, 70]}

In [ ]:
dp=pd.DataFrame(tb_dict) #DataFreme is a class, it uses uppercase letters in its name, it´s different of functions
dp

   name last_name  height  weight
0   jim      hook     150      50
1  juan       lin     160      60
2  jhon       par     170      70

# **Clase 17 de febrero 2026**

##base para empleados

In [ ]:
empleados=[] # lista vacia, en ella se agrega informacion sin tamaño definodo

e=False#bandera indicador para ciclo while

while e == False:
 try: # cuando no pasa nada se ingresa el dato solicitado
     tamaño=int(input("ingrese el tamaño de la lista: "))
     for i in range(tamaño):
       nombre=input("ingrese el nombre del empleado(a): ")

       empleados.append(nombre)
     print(empleados)
     e=True

 except ValueError:#detecta los fallos o errores para que el coiigo siga en ejecucion
    print("Error: Por favor. digita unicamente valores nuemrico enteros")

ingrese el tamaño de la lista: a
Error: Por favor. digita unicamente valores nuemrico enteros
ingrese el tamaño de la lista: 2
ingrese el nombre del empleado(a): maria
ingrese el nombre del empleado(a): 1
['maria', '1']

### Pandas

import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame() #se invoca el contructor

#agregar columnas

# forms 1
df["nombre"] = None
#forms 2
#df=df.assign(nombre=None)
df=df.assign(Edad=None)
#df
print(df)

Empty DataFrame
Columns: [nombre, Edad]
Index: []

In [ ]:
#consignar datos en el df (Dataframe)
#crear listas

nombres=["Luisa","Daniela","jorge"]
edades=[23,15,2]

df["nombre"]= nombres
df["Edad"]=edades

df

    nombre  Edad
0    Luisa    23
1  Daniela    15
2    jorge     2